[package]
name = "web_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
dns-lookup = "2.0.4"
reqwest = { version = "0.12.7", features = ["blocking"] }
threadpool = "1.8.1"
tokio = { version = "1", features = ["full"] }
